### PR TITLE
Build for Ubuntu Touch 20.04 Focal

### PR DESCRIPTION
**Pull request by JamiKettunen**
One of the current issues is https://github.com/timsueberkrueb/webber/issues/62 which is rather annoying for debugging, but other than that the app appears to work ok; I'm having difficulty with one particular website but I'm double-checking if it even works on 16.04

### CODE REVIEW

**Comment by timsueberkrueb** [comment]
Hi @JamiKettunen, thank you for your work! The PR looks good to me. My only concern is whether we should maintain compatibility with 16.04? 

Unfortunately, I can't really focus on this project at the moment. I can provide some feedback and upload new versions as needed.
I have invited you as a collaborator, but don't feel pressured to accept. Feel free to merge into master as you see fit. You can also take over publishing to the Open Store, if you want.

**Comment by JamiKettunen** [comment]
Regarding 16.04, do you have any plans to release any new versions there? OTA-25 will be the last update for it (releasing soonish) and after that it'll be entirely abandoned in favor of stability and feature development on 20.04, with effort in a month or two moving towards migrating the whole base to 22.04

Compat could maybe be retained, but would you be around to test new releases for `xenial`? I've not had it running on my devices for a while already since I've been working on the `focal` migration, and now daily it on my main phone :)

**Comment by timsueberkrueb** [comment]
Given that the community is relatively small and our time is limited, I agree we should probably just move on to `focal`.
If somebody cares about continued `xenial` support for Webber they would be very welcome to step up and do the work.

**Comment by JamiKettunen** [comment]
Ok seems the problematic site didn't work on 16.04 either, would you mind making a new v0.6.0 release and publish it for Focal on OpenStore? :)

**Comment by timsueberkrueb** [comment]
@JamiKettunen just uploaded it. Could you check if it works? I don't have focal flashed, yet.

**Comment by JamiKettunen** [comment]
@timsueberkrueb Seems to works great, thanks for the upload to focal ^^

**Pull request merged**
